### PR TITLE
Add Linux Swift 5.1 support

### PR DESCRIPTION
**Pull request by dnKaratzas**
Hi,

Im using your framework and I love it. I tried to use build on Docker swift 5.5 version and I got the following error:

> #14 10.61 /build/.build/checkouts/web3.swift/web3swift/src/Client/EthereumClient.swift:13:35: error: 'URLSessionConfiguration' is unavailable: This type has moved to the FoundationNetworking module. Import that module to use it.
#14 10.61     init(url: URL, sessionConfig: URLSessionConfiguration)
#14 10.61                                   ^~~~~~~~~~~~~~~~~~~~~~~
#14 10.61 Foundation.URLSessionConfiguration:2:18: note: 'URLSessionConfiguration' has been explicitly marked unavailable here
#14 10.61 public typealias URLSessionConfiguration = AnyObject
#14 10.61                  ^
#14 10.61 /build/.build/checkouts/web3.swift/web3swift/src/Client/EthereumClient.swift:50:25: error: 'URLSession' is unavailable: This type has moved to the FoundationNetworking module. Import that module to use it.
#14 10.61     public let session: URLSession
#14 10.61                         ^~~~~~~~~~
#14 10.61 Foundation.URLSession:2:18: note: 'URLSession' has been explicitly marked unavailable here
#14 10.61 public typealias URLSession = AnyObject

In Swift 5.1 on Linux, the network stuff is moved to `FoundationNetworking`
It looks like we need to import FoundationNetworking now, so I've done just that (conditionally, when it's available).

### CODE REVIEW

**Comment by dnKaratzas** [comment]
Tested on Linux Containers and works fine!

**Review by DarthMike — APPROVED** [review]
Thank you
